version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    #environment:
    #  - REDIS_HOST=redis
    #  - REDIS_PORT=6379
    #command: celery -A tasks worker --loglevel=INFO
    command: tail -f /dev/null
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app
    depends_on:
      - redis
