version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      
  mariadb:
    image: mariadb:11.3.2-jammy
    container_name: mariadb_container
    volumes:
        - './mariadb_data:/var/lib/mysql'
        - './mariadb_entrypoint:/docker-entrypoint-initdb.d'
  #  ports:
  #    - "3306:3306"
    healthcheck:
            #test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            interval: 10s
            timeout: 10s
            retries: 10  
    environment:
    
      #MYSQL_ROOT_PASSWORD: examplepassword
      #MYSQL_DATABASE: exampledb      
      #MYSQL_USER: exampleuser
      #MYSQL_PASSWORD: examplepassword
      MARIADB_DATABASE: classicmodels
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: examplepassword
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepassword                  
      

  python_app:
    build: 
      context: .
      dockerfile: Dockerfile
    build:
      args:
        HTTP_PROXY: http://10.1.1.68:808
        HTTPS_PROXY: http://10.1.1.68:808

    container_name: python_container
    command: tail -f /dev/null
    volumes:
       - '.:/app'    
    ports:
      - "5000:5000"
    depends_on:      
      mariadb:
         condition: service_healthy
      redis:
         condition: service_healthy

  locust:
    image: locustio/locust:2.23.1
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust      
    command: -f /mnt/locust/locustfile.py  -H http://python_app:5000


  locust-exporter:
    image: containersol/locust_exporter
    command: --locust.uri=http://locust:8089
    ports:
      - "9646:9646"


