version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    ports:
      - "3306:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10  
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword

  python_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: python_container
    ports:
      - "8000:5000"
    #depends_on:      
    #  mariadb:
    #     condition: service_healthy
    #  redis:
    #     condition: service_healthy

