version: '3'

services:
  reverse-proxy:
    image: traefik:2.11
    environment:
      - http_proxy=
      - https_proxy=
      - HTTPS_PROXY=
      - HTTP_PROXY=
      - no_proxy=blade6.ad.vayu.epfindia.gov.in,192.168.10.104,blade6,localhost,127.0.0.1,localaddress,.localdomain.com,172.17.0.11,172.30.1.1,docker-registry.default.svc.cluster.local,10.0.0.0/8
      - NO_PROXY=blade6.ad.vayu.epfindia.gov.in,192.168.10.104,blade6,localhost,127.0.0.1,localaddress,.localdomain.com,172.17.0.11,172.30.1.1,docker-registry.default.svc.cluster.local,10.0.0.0/8


    command:
    #- '--log.level=DEBUG'
    #- '--api=true'
    #- '--api.debug=true'
    #- '--api.dashboard=true'
    #- '--api.insecure'
    #- '--configFile=/etc/traefik/traefik.yml'
    #- '--providers.docker.endpoint=unix:///var/run/docker.sock'
    #- '--providers.docker.exposedbydefault=false'
    #- '--entrypoints.web.address=:80'
    #- '--entrypoints.websecure.address=:443'
    #- '--entrypoints.websecure.http.tls=true'
    command: tail -f /dev/null
    ports:
      - "84:84"
      - "8084:8080"
      - "2443:2443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik_config:/etc/traefik
      - ./certs:/etc/certs/

    networks:
      - default
    

networks:
  default:
     external: true
     name: blade6_default
    

