---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
#background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
#background: /icons/nature-landscape.jpg
title: Homepage
#startUrl: https://10.1.1.55/homepage/
#base: /homepage/
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
